modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"
[[mods]]
modId="goety"
version="${file.jarVersion}"
displayName="Goety"
displayURL="https://github.com/Polarice3/Goety-2"
logoFile="Goety.png" #optional
credits="Tutorial/Help: GentlemanRevvnar, Technovision, Cy4's Modding, TelepathicGrunt, diesieben07. Bug Testing: Mich705, pantman687, glacial_flower. Necromancer Servant texture by frosty_gg. Chinese Translation: Player_7, Japanese Translation: SAGA, Russian Translation: .cool_nickname"
authors="Polarice3"
description='''
Goety adds a bunch of new Mobs that can help or hinder players and a magic system that can provides a player a different way of combat!
'''
[[dependencies.goety]] #optional
modId="forge" #mandatory

mandatory=true #mandatory

versionRange="${neo_version_range}" #mandatory

ordering="NONE"

side="BOTH"

[[dependencies.goety]]
modId = "curios"
mandatory = true
versionRange = "[1.20-5.3.4,)"
side = "BOTH"

[[dependencies.goety]]
modId="minecraft"

mandatory=true

versionRange="${minecraft_version_range}"

ordering="NONE"

side="BOTH"
