modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="goety"
version="${file.jarVersion}"
displayName="Goety"
displayURL="https://github.com/Polarice3/Goety-2"
logoFile="Goety.png" #optional
credits="Tutorial/Help: GentlemanRevvnar, Technovision, Cy4's Modding, TelepathicGrunt, diesieben07. Bug Testing: Mich705, pantman687."
authors="Polarice3"
description='''
Goety adds a bunch of new Mobs that can help or hinder players and a magic system that can provides a player a different way of combat!
'''
[[dependencies.goety]] #optional
    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[43,)" #mandatory

    ordering="NONE"

    side="BOTH"

[[dependencies.goety]]
    modId = "curios"
    mandatory = true
    versionRange = "[1.19-5.1.0.4,)"
    side = "BOTH"

[[dependencies.goety]]
    modId="minecraft"

    mandatory=true

    versionRange="[1.19.2,1.20)"

    ordering="NONE"

    side="BOTH"
